### ISSUE TITLE
UnboundLocalError cannot access local variable 'command_name'

### ISSUE THREAD

**Issue by quatronostro** [Torantulino/Auto-GPT#1205]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I have to mention that I'm not good at programing. So when I encountred some error it takes sometimes days to solve that. Please help me.

This is my steps:
1. I open cmd and enter cd auto-gpt command
2. I type python scripts/main.py and press enter
3. I set my gpt name so program ask me to continue with that and I press "y"
4. AUTO-GPT THOUGHTS:/ REASONING:/ PLAN:/ CRITICISM: -> No problems with these titles.
5. After CRITICISM: , I'm encountring this error:

Error:
  module 'command' has no attribute 'get_command'
Traceback (most recent call last):
  File "C:\Users\Berke\Auto-GPT\scripts\main.py", line 444, in <module>
    main()
  File "C:\Users\Berke\Auto-GPT\scripts\main.py", line 375, in main
    f"COMMAND = {Fore.CYAN}{command_name}{Style.RESET_ALL}  ARGUMENTS = {Fore.CYAN}{arguments}{Style.RESET_ALL}")
                            ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'command_name' where it is not associated with a value

![image](https://user-images.githubusercontent.com/93223660/231899709-b824bb5c-ca58-441f-86c3-dc4de41bf4d5.png)

### Current behavior 😯

Error:
  module 'command' has no attribute 'get_command'
Traceback (most recent call last):
  File "C:\Users\Berke\Auto-GPT\scripts\main.py", line 444, in <module>
    main()
  File "C:\Users\Berke\Auto-GPT\scripts\main.py", line 375, in main
    f"COMMAND = {Fore.CYAN}{command_name}{Style.RESET_ALL}  ARGUMENTS = {Fore.CYAN}{arguments}{Style.RESET_ALL}")
                            ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'command_name' where it is not associated with a value

### Expected behavior 🤔

I think it has to continue like with "NEXT ACTİON" something like that, am I right?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by quatronostro** [comment]
Guys, today I tried to delete auto-gpt and install again and its working properly now 😁
