### ISSUE TITLE
开启后，无法和openai取得联系，报错了

### ISSUE THREAD

**Issue by liliwen365** [Torantulino/Auto-GPT#1221]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\01 软件\29 ChatGPT\Auto-GPT-0.1.2\scripts\main.py", line 442, in <module>
    main()
  File "D:\01 软件\29 ChatGPT\Auto-GPT-0.1.2\scripts\main.py", line 346, in main
    assistant_reply = chat.chat_with_ai(
  File "D:\01 软件\29 ChatGPT\Auto-GPT-0.1.2\scripts\chat.py", line 73, in chat_with_ai
    relevant_memory = permanent_memory.get_relevant(str(full_message_history[-9:]), 10)
  File "D:\01 软件\29 ChatGPT\Auto-GPT-0.1.2\scripts\memory\local.py", line 112, in get_relevant
    embedding = get_ada_embedding(text)
  File "D:\01 软件\29 ChatGPT\Auto-GPT-0.1.2\scripts\memory\base.py", line 14, in get_ada_embedding
    return openai.Embedding.create(input=[text], model="text-embedding-ada-002")["data"][0]["embedding"]
  File "C:\Users\admin\Envs\env_gpt\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "C:\Users\admin\Envs\env_gpt\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\admin\Envs\env_gpt\lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "C:\Users\admin\Envs\env_gpt\lib\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000122B392DBB0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接 的主机没有反应，连接尝试失败。'))

### Current behavior 😯

我开启后，一段时间后报错，如上：
(env_gpt) D:\01 软件\29 ChatGPT\Auto-GPT-0.1.2>python scripts/main.py --gpt3only
GPT3.5 Only Mode:  ENABLED
Welcome back!  Would you like me to return to being xiaoli?
Continue with the last settings?
Name:  xiaoli
Role:  everyone
Goals: ['hello']
Continue (y/n): y
Using memory of type: LocalCache
\ Thinking...
然后就尝试了5次就报错了
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000122B392DBB0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接 的主机没有反应，连接尝试失败。'))

### Expected behavior 🤔

没有和openai取得联系

### Your prompt 📝

```yaml
# Paste your prompt here
```
没有和openai取得联系

**Comment by liliwen365** [comment]
感谢，你提出的解决方案http需要改成https，这样可以解决~~，感谢！！！

**Comment by richbeales** [comment]
Apologies, english only.  I can't support if I can't read the issue.
