### ISSUE TITLE
file 'auto-gpt.json' does not exist. Failed to get response after 5 retries 

### ISSUE THREAD

**Issue by iva-nova-e-katerina** [Torantulino/Auto-GPT#1248]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

EXECUTE_LOCAL_COMMANDS=True
...
python3 scripts/main.py --continuous --gpt3only

### Current behavior 😯

```
Continuous Mode:  ENABLED
WARNING:  Continuous mode is not recommended. It is potentially dangerous and may cause your AI to run forever or carry out actions you would not usually authorise. Use at your own risk.
GPT3.5 Only Mode:  ENABLED
Welcome back!  Would you like me to return to being ai?
Continue with the last settings?
Name:  ai
Role:  increasing
Goals: ['increasing net worth.']
Continue (y/n): y
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/home/user/Auto-GPT/scripts/main.py", line 461, in <module>
    main()
  File "/home/user/Auto-GPT/scripts/main.py", line 365, in main
    assistant_reply = chat.chat_with_ai(
  File "/home/user/Auto-GPT/scripts/chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/home/user/Auto-GPT/scripts/llm_utils.py", line 50, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries
user@user-VirtualBox:~/Auto-GPT$ git pull
Already up to date.

```

### Expected behavior 🤔

More informative error message. Does openai API inaccessible or what?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by miwandnaj** [comment]
What do you get if you run `python scripts/main.py --debug`. I am currently getting rate limit errors. `Error:  API Rate Limit Reached. Waiting 20 seconds...` even though I am running gpt3only command.

**Comment by huakaiwuyeshu** [comment]
同样的问题，运行 debug 后，得到相同的错误。
Error:  API Rate Limit Reached. Waiting 20 seconds...

**Comment by Youcancallmexy** [comment]
me too

**Comment by JuroOravec** [comment]
Duplicate of https://github.com/Torantulino/Auto-GPT/issues/1189. @iva-nova-e-katerina would you close this issue if it indeed is the same thing?

**Comment by iva-nova-e-katerina** [comment]
dublicate of #1304
