### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by qwe2950531** [Torantulino/Auto-GPT#1275]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

just get start

### Current behavior 😯

most recent call last):
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\666\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\666\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\666\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

### Expected behavior 🤔

i got some proxy problem,and i;m in chinese so need proxy

代理问题呀有大佬帮忙看看么

### Your prompt 📝

```yaml
# Paste your prompt here
```
can't prompt

**Comment by chenfengshijie** [comment]
same problem插眼

**Comment by ban-jobs** [comment]
modify [Your python3 dir]\lib\site-packages\openai\api_requestor.py

```
...
def _prepare_request_raw
...
        headers = self.request_headers(method, headers, request_id)
        # Set local vpn proxy_pool
        proxy_pool = {
            'http': 'http://127.0.0.1:33210', 
            'https': 'http://127.0.0.1:33210'
        }
...
       # Add proxy_pool
       return abs_url, headers, proxy_pool, data
...
def request_raw
...
       # Add proxy_pool
       abs_url, headers, proxy_pool, data = self._prepare_request_raw
...
       result = _thread_context.session.request(
                method,
                abs_url,
                headers=headers,
                # Add proxy_pool
                proxies=proxy_pool,

```

**Comment by qwe2950531** [comment]
I' did it already but did't sove the problem ,because it's just sove the openai-sdk access api proxy problem

>

**Comment by ban-jobs** [comment]
> 
please paste all error logs

**Comment by qwe2950531** [comment]
> > 
> 
> please paste all error logs
Traceback (most recent call last):
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\connectionpool.py", line 997, in _prepare_proxy
    conn.connect()
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\666\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\666\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\666\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\requests\adapters.py", line 495, in send
    resp = conn.urlopen(
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSL
Error(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\projects\ai-relate\Auto-GPT\scripts\main.py", line 441, in <module>
    main()
  File "D:\work\projects\ai-relate\Auto-GPT\scripts\main.py", line 304, in main
    agent.start_interaction_loop()
  File "D:\work\projects\ai-relate\Auto-GPT\scripts\main.py", line 345, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "D:\work\projects\ai-relate\Auto-GPT\scripts\chat.py", line 77, in chat_with_ai
    next_message_to_add_index, current_tokens_used, insertion_index, current_context = generate_context(
  File "D:\work\projects\ai-relate\Auto-GPT\scripts\chat.py", line 40, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "D:\work\projects\ai-relate\Auto-GPT\scripts\token_counter.py", line 17, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\tiktoken\load.py", line 114, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\tiktoken\load.py", line 46, in read_file_cached
    contents = read_file(blobpath)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\tiktoken\load.py", line 24, in read_file
    return requests.get(blobpath).content
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\work\projects\ai-relate\Auto-GPT\nees\lib\site-packages\requests\adapters.py", line 570, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLErro
r(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by qwe2950531** [comment]
> maybe you can try:
> 
> ```python
> if __name__ == "__main__":
>     import os
>     os.environ['HTTP_PROXY'] = "http://localhost:7890"
>     os.environ['HTTPS_PROXY'] = "http://localhost:7890"
>     main()
> ```
> 
> the file is in Scripts/main.py


still not work

**Comment by x18-1** [comment]
Do you use clash,i use clash,through the prot(7890) i can access the openai's website

**Comment by chenfengshijie** [comment]
> Do you use clash,i use clash,through the prot(7890) i can access the openai's website

thanks,I use clash,that's ok for me.

**Comment by qwe2950531** [comment]
> Do you use clash,i use clash,through the prot(7890) i can access the openai's website

i use v2ray through 1081  same thing

**Comment by x18-1** [comment]
> > Do you use clash,i use clash,through the prot(7890) i can access the openai's website
> 
> i use v2ray through 1081 same thing

change 7890 to 1081 still didn't work?

**Comment by sonnyfu** [comment]
solved now?

**Comment by Leopold-01** [comment]
same error ，i solve it.
using clash , port 7890 , global , US

before ```python -m autogpt```
set proxy for your terminal
```set http_proxy=http://127.0.0.1:7890```
```set http_proxy=http://127.0.0.1:7890```
then run ```python -m autogpt```
it works !!

**Comment by Garfielding** [comment]
> maybe you can try:
> 
> ```python
> if __name__ == "__main__":
>     import os
>     os.environ['HTTP_PROXY'] = "http://localhost:7890"
>     os.environ['HTTPS_PROXY'] = "http://localhost:7890"
>     main()
> ```
> 
> the file is in Scripts/main.py

it works, thanks

**Comment by z-x-x136** [comment]
> 修改 [Your python3 dir]\lib\site-packages\openai\api_requestor.py
> 
> ```
> ...
> def _prepare_request_raw
> ...
>         headers = self.request_headers(method, headers, request_id)
>         # Set local vpn proxy_pool
>         proxy_pool = {
>             'http': 'http://127.0.0.1:33210', 
>             'https': 'http://127.0.0.1:33210'
>         }
> ...
>        # Add proxy_pool
>        return abs_url, headers, proxy_pool, data
> ...
> def request_raw
> ...
>        # Add proxy_pool
>        abs_url, headers, proxy_pool, data = self._prepare_request_raw
> ...
>        result = _thread_context.session.request(
>                 method,
>                 abs_url,
>                 headers=headers,
>                 # Add proxy_pool
>                 proxies=proxy_pool,
> ```



Do you replace everything in the prepare request raw function？

**Comment by pantomath-jin** [comment]
I am not familiar with these network things. I was working on windows, autogpt ver 0.2.2, and used cmd as a terminal. These are the solution i’ve tried:
command on cmd:
`set http_proxy=http://127.0.0.1:7890`
`set https_proxy=http://127.0.0.1:7890`

and
change the __main__.py in autogpt to: 
```python
import autogpt.cli
import os
if __name__ == "__main__":
    os.environ['HTTP_PROXY'] = "http://localhost:7890"
    os.environ['HTTPS_PROXY'] = "http://localhost:7890"
    autogpt.cli.main()
```
and it didn't work.

which leads these question:
1. Which one fits my situation, or should I apply them both?
2. Does the “set” command work in cmd? How about the Ubuntu terminal?
3. Should I change the “localhost” part or “127.0.0.1:7890” part, and how?
4. Is there other possible solution?

**Comment by z-x-x136** [comment]
> 修改 [Your python3 dir]\lib\site-packages\openai\api_requestor.py
> 
> ```
> ...
> def _prepare_request_raw
> ...
>         headers = self.request_headers(method, headers, request_id)
>         # Set local vpn proxy_pool
>         proxy_pool = {
>             'http': 'http://127.0.0.1:33210', 
>             'https': 'http://127.0.0.1:33210'
>         }
> ...
>        # Add proxy_pool
>        return abs_url, headers, proxy_pool, data
> ...
> def request_raw
> ...
>        # Add proxy_pool
>        abs_url, headers, proxy_pool, data = self._prepare_request_raw
> ...
>        result = _thread_context.session.request(
>                 method,
>                 abs_url,
>                 headers=headers,
>                 # Add proxy_pool
>                 proxies=proxy_pool,
> ```

(AutoGPT) E:\chatGPT\AutoGPT2\Auto-GPT-0.2.2>python -m autogpt --gpt3only 
GPT3.5 Only Mode:  ENABLED
NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by p
rinting messages here. If you don't wish to see this message, you can run Auto-GPT with 
the --skip-news flag
Welcome back!  Would you like me to return to being AI金融?
Continue with the last settings?
Name:  AI金融
Role:  用python写一个爬取关于美联储的最新消息的程序
Goals: ['把爬取的最新内容通过txt文件的形式及时保存在本地路径中，并且把内容翻译为中文', '
最新内容的时间范围是从2023年1月开始到爬取数据的当天', '爬取的信息可以是新闻，可以是美国 
官网上的信息', '不能读取本地 ', '把实现爬取的程序写入本地中']
Continue (y/n): y
Using memory of type:  LocalCache
Using Browser:  chrome
Traceback (most recent call last):
  File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\click\core.py", line 1404, i
n invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\click\core.py", line 760, in
 invoke
    return __callback(*args, **kwargs)
  File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\click\decorators.py", line 2
6, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "E:\chatGPT\AutoGPT2\Auto-GPT-0.2.2\autogpt\cli.py", line 151, in main
    agent.start_interaction_loop()
  File "E:\chatGPT\AutoGPT2\Auto-GPT-0.2.2\autogpt\agent\agent.py", line 75, in start_in
teraction_loop
    assistant_reply = chat_with_ai(
  File "E:\chatGPT\AutoGPT2\Auto-GPT-0.2.2\autogpt\chat.py", line 159, in chat_with_ai  
    assistant_reply = create_chat_completion(
  File "E:\chatGPT\AutoGPT2\Auto-GPT-0.2.2\autogpt\llm_utils.py", line 93, in create_cha
t_completion
    response = openai.ChatCompletion.create(
  File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\openai\api_resources\chat_co
mpletion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\openai\api_resources\abstrac
t\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\openai\api_requestor.py", li
ne 216, in request
    result = self.request_raw(
  File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\openai\api_requestor.py", li
ne 521, in request_raw
    result = _thread_context.session.request(
  File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\requests\sessions.py", line 
577, in request
    settings = self.merge_environment_settings(
  File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\requests\sessions.py", line 
758, in merge_environment_settings
    no_proxy = proxies.get("no_proxy") if proxies is not None else None
AttributeError: 'bytes' object has no attribute 'get'


This is the output after I set it up?

**Comment by z-x-x136** [comment]
> 修改 [你的 python3 目录]\lib\site-packages\openai\api_requestor.py
> 
> ```
> ...
> def _prepare_request_raw
> ...
>         headers = self.request_headers(method, headers, request_id)
>         # Set local vpn proxy_pool
>         proxy_pool = {
>             'http': 'http://127.0.0.1:33210', 
>             'https': 'http://127.0.0.1:33210'
>         }
> ...
>        # Add proxy_pool
>        return abs_url, headers, proxy_pool, data
> ...
> def request_raw
> ...
>        # Add proxy_pool
>        abs_url, headers, proxy_pool, data = self._prepare_request_raw
> ...
>        result = _thread_context.session.request(
>                 method,
>                 abs_url,
>                 headers=headers,
>                 # Add proxy_pool
>                 proxies=proxy_pool,
> ```

(AutoGPT) E:\chatGPT\AutoGPT2\Auto-GPT-0.2.2>python -m autogpt --gpt3only
GPT3.5 Only Mode: ENABLED
新闻：欢迎使用 Auto-GPT！我们将通过在此处打印消息让您了解最新消息和功能
。如果您不想看到此消息，可以使用
--skip-news 标志运行 Auto-GPT
欢迎回来！你想让我回到AI金融吗？
继续最后的设置？
名称：AI金融
角色：用python编写一个关于美联储的最新消息的程序
目标：['把卸载的最新内容通过txt文件的格式及时间保存在本地中场容翻译为中文', '
最新内容的时间范围取围是从2023年1月开始到取数据的当天', '取的信息可以是新闻，可以是美国官网上的取信息', '不能读本狗地方', '把狗
地方的程序写入本地']
继续（是/否）：是
使用类型的内存：LocalCache
使用浏览器：
回溯（最近一次调用最后一次）：
文件“D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\click\core.py”，第 1404 行，我
调用
return ctx.invoke(self.callback, * *ctx.params)
文件“D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\click\core.py”，第 760 行，在
调用
返回 __callback(*args, **kwargs)
文件“D: \anaconda\Anaconda\envs\AutoGPT\lib\site-packages\click\decorators.py", line 2 6
, in new_func
return f(get_current_context(), *args, **kwargs)
File "E:\chatGPT\AutoGPT2 \Auto-GPT-0.2.2\autogpt\cli.py”，第 151 行，在主
agent.start_interaction_loop()
文件“E:\chatGPT\AutoGPT2\Auto-GPT-0.2.2\autogpt\agent\agent.py "，第 75 行，在
start_interaction_loop中
assistant_reply = chat_with_ai(
文件“E:\chatGPT\AutoGPT2\Auto-GPT-0.2.2\autogpt\chat.py”，第 159 行，在 chat_with_ai assistant_reply
= create_chat_completion(
文件“E:\chatGPT\AutoGPT2\Auto-GPT- 0.2.2\autogpt\llm_utils.py", line 93, in create_cha
t_completion
response = openai.ChatCompletion.create(
File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\openai\api_resources\
chat_completion .py”，第 25 行，在创建
返回 super().create(*args, **kwargs)
文件“D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\openai\api_resources\abstrac
t\engine_api_resource .py”，第 153 行，在创建
响应中，_, api_key = requestor.request(
文件“D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\openai\api_requestor.py”，第 216 行，
请求
结果 = self.request_raw(
文件“D:\anaconda\Anaconda\envs\AutoGPT \lib\site-packages\openai\api_requestor.py", line
521, in request_raw
result = _thread_context.session.request(
File "D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\requests\sessions .py”，第
577 行，在请求
设置 = self.merge_environment_settings(
文件“D:\anaconda\Anaconda\envs\AutoGPT\lib\site-packages\requests\sessions.py”，第 758 行，
在 merge_environment_settings
no_proxy = proxies. get("no_proxy") 如果代理不是 None else None
AttributeError: 'bytes'对象没有属性“get”

This is the output after I set it up.How to solve it?
