### ISSUE TITLE
Error message generated in the middle of a task the AutoGPT was doing goal tasks

### ISSUE THREAD

**Issue by Shangooriginal** [Torantulino/Auto-GPT#1356]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Asked it to do any goal task

### Current behavior 😯

This error is generated by 20 mins 
Traceback (most recent call last):
  File "C:\Users\XXXX\Documents\AutoGPT\Auto-GPT\scripts\main.py", line 441, in <module>
    main()
  File "C:\Users\XXXX\Documents\AutoGPT\Auto-GPT\scripts\main.py", line 304, in main
    agent.start_interaction_loop()
  File "C:\Users\XXXX\Documents\AutoGPT\Auto-GPT\scripts\main.py", line 345, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\XXXX\Documents\AutoGPT\Auto-GPT\scripts\chat.py", line 73, in chat_with_ai
    relevant_memory = '' if len(full_message_history) ==0 else  permanent_memory.get_relevant(str(full_message_history[-9:]), 10)
  File "C:\Users\XXXX\Documents\AutoGPT\Auto-GPT\scripts\memory\local.py", line 112, in get_relevant
    embedding = get_ada_embedding(text)
  File "C:\Users\XXXX\Documents\AutoGPT\Auto-GPT\scripts\memory\base.py", line 14, in get_ada_embedding
    return openai.Embedding.create(input=[text], model="text-embedding-ada-002")["data"][0]["embedding"]
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID f171690ff212240429afed5d6b50988e in your message.) {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID f171690ff212240429afed5d6b50988e in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID f171690ff212240429afed5d6b50988e in your message.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Fri, 14 Apr 2023 16:41:56 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'openai-organization': 'user-79acdkyzpj0roromhowfrexg', 'openai-processing-ms': '30029', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '3000', 'x-ratelimit-remaining-requests': '2999', 'x-ratelimit-reset-requests': '20ms', 'x-request-id': 'f171690ff212240429afed5d6b50988e', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7b7d6571ad270635-LHR', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}

### Expected behavior 🤔

Should have finished the goals/tasks it was given. The program running faced an issue while processing a task. The server that the program was communicating with encountered an error. You can try running the program again, and if the problem continues, you might need to contact the support team for help.

### Your prompt 📝

```yaml
# Paste your prompt here
```
Search the internet for a specific available information

**Comment by zhongyinghua** [comment]
Hey, have you solved this issue? I got the same error when the task  looks like it's almost done. 
Except for the difference in personal information, the "Current behavior" we encountered is almost exactly the same. 
I'm so confused now...
