### ISSUE TITLE
Error: python setup.py egg_info did not run successfully (macOS)

### ISSUE THREAD

**Issue by aodrasa** [Torantulino/Auto-GPT#138]
Continue to get the following error indicating requirements.txt is missing. Has anyone found a fix for this yet? 
Tried running in a venv and still no luck. 

```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/0x/1gmts4910vs5kjmbz0shlj3h0000gn/T/pip-install-dgt_ly2f/googlesearch-python_b107b596909345f78e68a5ebb615d152/setup.py", line 6, in <module>
          with open("requirements.txt") as fh:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by StewartVanDusen** [comment]
How did you get this issue resolved?

**Comment by albermoon** [comment]
I have the same problem, Anyone has found any solutions or any place where it is fixed?
