### ISSUE TITLE
NameError: name 'Config' is not defined while running python -m autogpt

### ISSUE THREAD

**Issue by wellswei** [Torantulino/Auto-GPT#1429]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

(base) XX@XXiMac Auto-GPT % python -m autogpt
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/XX/Documents/GitHub/Auto-GPT/autogpt/__main__.py", line 12, in <module>
    from autogpt import commands as cmd
  File "/Users/XX/Documents/GitHub/Auto-GPT/autogpt/commands.py", line 9, in <module>
    cfg = Config()
NameError: name 'Config' is not defined

### Your prompt 📝

```yaml
(base) XX@XXiMac Auto-GPT % python -m autogpt
```

**Comment by Gincioks** [comment]
Add from autogpt.config import Config to autogpt/commands.py file before cfg = Config()

**Comment by mencelot** [comment]
> Add `from autogpt.config import Config` to autogpt/commands.py file before `cfg = Config()`

That worked for me thanks

**Comment by Jarrod-Herbert** [comment]
Worked for me as well thanks!

**Comment by ASVN2** [comment]
But It didn't work for me ?

**Comment by richbeales** [comment]
closing as superseded by v0.2.0
