### ISSUE TITLE
Hi, could you please help me with this: ModuleNotFoundError: No module named 'autogpt'

### ISSUE THREAD

**Issue by Fation87** [Torantulino/Auto-GPT#1434]
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```
![image](https://user-images.githubusercontent.com/130802664/232165739-51444712-5f8d-4cd3-be38-3d729bd9a9b7.png)

**Comment by Fation87** [comment]
i lunched the main.py , tried also with python3

**Comment by neutralvision** [comment]
run in:
`C:\Users\inter\Downloads\Auto-GPT-master\Audot-GPT-master`

instead of:
`C:\Users\inter\Downloads\Auto-GPT-master`

**Comment by Fation87** [comment]
![image](https://user-images.githubusercontent.com/130802664/232167724-521e84e6-778c-4abc-8fdb-a1372edfcc2a.png)

**Comment by shaiss** [comment]
Same here 
<img width="907" alt="WindowsTerminal_qE9qtApnZy" src="https://user-images.githubusercontent.com/113060/232179209-24215eff-c573-4302-9aa6-93f7daa05026.png">

**Comment by rrtt2323** [comment]
me too!

**Comment by Qoyyuum** [comment]
@Fation87 do this:
```
cd C:\Users\inter\Downloads\Auto-GPT-master\Auto-GPT-master
python -m autogpt
```
That should fix it.

**Comment by mikkovedru** [comment]
On Linux, if using the `stable` branch like recommended, the error can be fixed by:
1. going to `scripts` subdirectory
2. running `python -m main`.

Well, at least it gets it running. Otherwise, I encounter the same "**RuntimeError: Failed to get response after 5 retries**" error I get on `master` branch as well:
```
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mikko/Desktop/Copy/Projects/Programming/Auto-GPT/scripts/main.py", line 465, in <module>
    main()
  File "/home/mikko/Desktop/Copy/Projects/Programming/Auto-GPT/scripts/main.py", line 328, in main
    agent.start_interaction_loop()
  File "/home/mikko/Desktop/Copy/Projects/Programming/Auto-GPT/scripts/main.py", line 369, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "/home/mikko/Desktop/Copy/Projects/Programming/Auto-GPT/scripts/chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/home/mikko/Desktop/Copy/Projects/Programming/Auto-GPT/scripts/llm_utils.py", line 50, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries
```

**Comment by richbeales** [comment]
closing as superseded by v0.2.0
