### ISSUE TITLE
 Command google returned: Error: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by pythonerrnewer** [Torantulino/Auto-GPT#1467]
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Qoyyuum** [comment]
@pythonerrnewer Can you run the script again but add --debug please?

Please share the result.

您可以再次运行该脚本，但请添加 --debug 吗？

请分享结果

**Comment by pythonerrnewer** [comment]
> @pythonerrnewer您可以再次运行脚本但请添加 --debug 吗？
> 
> 请分享结果。
> 
> 您可以再次运行该脚本，但请添加 --debug 吗？
> 
> 请分享结果

Debug Mode:  ENABLED
Welcome back!  Would you like me to return to being a?
Continue with the last settings?
Name:  a
Role:  找出质子交换膜技术最先进的5家公司，分析其公司产品的特点和优劣，总结成一张表格
Goals: ['找出质子交换膜技术最先进的5家公司', '分析其公司产品的特点和优劣', '总结成一张表格', '所有的回答用中文输出']
Continue (y/n): y
Using memory of type: LocalCache
  Token limit: 4000
  Memory Stats: (0, (0, 1536))
  Token limit: 4000
  Send Token Count: 953
  Tokens remaining for response: 3047
  ------------ CONTEXT SENT TO AI ---------------
  System: The current time and date is Sat Apr 15 12:45:00 2023

  System: This reminds you of these events from your past:




  User: Determine which next command to use, and respond using the format specified above:

  ----------- END OF CONTEXT ----------------
Creating chat completion with model gpt-3.5-turbo, temperature 1.0, max_tokens 3047
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000209817D0D90>, 'Connection to api.openai.com timed out. (connect timeout=600)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000209817D0D90>, 'Connection to api.openai.com timed out. (connect timeout=600)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000209817D0D90>, 'Connection to api.openai.com timed out. (connect timeout=600)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\auto-gpt\Auto-GPT-master\autogpt\__main__.py", line 572, in <module>
    main()
  File "H:\auto-gpt\Auto-GPT-master\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "H:\auto-gpt\Auto-GPT-master\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "H:\auto-gpt\Auto-GPT-master\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "H:\auto-gpt\Auto-GPT-master\autogpt\llm_utils.py", line 39, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 526, in request_raw
    raise error.Timeout("Request timed out: {}".format(e)) from e
openai.error.Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000209817D0D90>, 'Connection to api.openai.com timed out. (connect timeout=600)'))

H:\auto-gpt\Auto-GPT-master>

**Comment by Qoyyuum** [comment]
Thanks @pythonerrnewer 

It looks like you cannot connect to OpenAI API endpoints. Can you try with a VPN?

看起来您无法连接到 OpenAI API 端点。 您可以尝试使用 VPN 吗？

**Comment by richbeales** [comment]
please keep discussions to English only so that the maintainers can assist you.
OpenAI's APIs are not supported in some countries.  Closing as not an AutoGPT issue

**Comment by pythonerrnewer** [comment]
> Thanks @pythonerrnewer
> 
> It looks like you cannot connect to OpenAI API endpoints. Can you try with a VPN?
> 
> 看起来您无法连接到 OpenAI API 端点。 您可以尝试使用 VPN 吗？

I used VPN and it was a global proxy, but the same problem still occurred. Additionally, I am able to access the openai website smoothly using this node

**Comment by wissne** [comment]
Same issue for me

**Comment by olymax** [comment]
会不会是代理的协议不是http或者https呢？
看来一下报错：
“ Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com',
port=443)”
看来是https.
暂时没有其他办法。有没有大神可以解决一下这个事情。

ARG ***@***.***> 于2023年4月15日周六 20:54写道：

**Comment by wissne** [comment]
You can try below command in the terminal
curl cip.cc

**Comment by fei15115** [comment]
Same issue same global proxy.
Able to using openai on web.
Not sure if there is any limit on openai api?
Or should I config the billing page with my credit info?

**Comment by zxy177280210** [comment]
这个博客可以解决这个问题：https://blog.csdn.net/weixin_43744732/article/details/130190697

**Comment by fei15115** [comment]
您好，我已经收到您的邮件，我会尽快查看回复，谢谢！

**Comment by 949491819** [comment]
![image](https://user-images.githubusercontent.com/44401438/232437524-2829b3f8-c703-4ed7-9061-768021b79b28.png)
