### ISSUE TITLE
[ISSUE WITH NEW SCRIPTS UPDATE] Devs, since the update an hour ago this is a persistent issue. 

### ISSUE THREAD

**Issue by aodrasa** [Torantulino/Auto-GPT#165]
Had no issues until the Scrips folder was updated. Any directions on how to solve this?

```
Continuous Mode:  ENABLED
WARNING:  Continuous mode is not recommended. It is potentially dangerous and may cause your AI to run forever or carry out actions you would not usually authorise. Use at your own risk.
Speak Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
Traceback (most recent call last):
  File "/Users/adamsardo/Auto-GPT/scripts/main.py", line 275, in <module>
    prompt = construct_prompt()
  File "/Users/adamsardo/Auto-GPT/scripts/main.py", line 178, in construct_prompt
    config = prompt_user()
  File "/Users/adamsardo/Auto-GPT/scripts/main.py", line 192, in prompt_user
    print_to_console(
  File "/Users/adamsardo/Auto-GPT/scripts/main.py", line 30, in print_to_console
    speak.say_text(f"{title}. {content}")
  File "/Users/adamsardo/Auto-GPT/scripts/speak.py", line 45, in say_text
    success = eleven_labs_speech()
TypeError: eleven_labs_speech() missing 1 required positional argument: 'text'
```

**Comment by Torantulino** [comment]
Sorry about that, should be all fixed now!
