### ISSUE TITLE
MCI error message in speech mode

### ISSUE THREAD

**Issue by deronkel82** [Torantulino/Auto-GPT#191]
When using speed mode it works once and then the following error occurs:

←[32mSpeak Mode:  ←[0mENABLED

    Error 263 for command:
        open speech.mpeg
    Gerät ist nicht geöffnet oder wird vom MCI nicht erkannt.

    Error 263 for command:
        close speech.mpeg
    Gerät ist nicht geöffnet oder wird vom MCI nicht erkannt.
Failed to close the file: speech.mpeg
Traceback (most recent call last):
  File "D:\KI\Auto-GPT-master\scripts\main.py", line 275, in <module>
    prompt = construct_prompt()
  File "D:\KI\Auto-GPT-master\scripts\main.py", line 164, in construct_prompt
    print_to_console(
  File "D:\KI\Auto-GPT-master\scripts\main.py", line 30, in print_to_console
    speak.say_text(f"{title}. {content}")
  File "D:\KI\Auto-GPT-master\scripts\speak.py", line 45, in say_text
    success = eleven_labs_speech(text)
  File "D:\KI\Auto-GPT-master\scripts\speak.py", line 27, in eleven_labs_speech
    playsound("speech.mpeg")
  File "C:\Users\heins\AppData\Local\Programs\Python\Python310\lib\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "C:\Users\heins\AppData\Local\Programs\Python\Python310\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 263 for command:
        open speech.mpeg
    Gerät ist nicht geöffnet oder wird vom MCI nicht erkannt.

**Comment by user41pp** [comment]
Downgrading playsound fixed it for me

`pip install playsound==1.2.2`

See [this stackoverflow thread](https://stackoverflow.com/questions/68826091/the-specified-device-is-not-open-or-is-not-recognized-by-mci#:~:text=So%20what%20actually%20worked%20is%20that%20the%20recent,install%20playsound%3D%3D1.2.2%20and%20this%20should%20do%20the%20work.)

**Comment by deronkel82** [comment]
This worked! Thanks!

**Comment by alybaba32** [comment]
Worked!

**Comment by alybaba32** [comment]
> Downgrading playsound fixed it for me
> 
> `pip install playsound==1.2.2`
> 
> See [this stackoverflow thread](https://stackoverflow.com/questions/68826091/the-specified-device-is-not-open-or-is-not-recognized-by-mci#:~:text=So%20what%20actually%20worked%20is%20that%20the%20recent,install%20playsound%3D%3D1.2.2%20and%20this%20should%20do%20the%20work.)

Worked!
