### ISSUE TITLE
Wont go past 5th instruction.

### ISSUE THREAD

**Issue by ExoSilica** [Torantulino/Auto-GPT#332]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Hi, after I completed the 5th goal for the bot it started generating this:

### Current behavior 😯

Basically just closed.

### Expected behavior 🤔

Continue and provide output.

### Your prompt 📝

```yaml
Traceback (most recent call last):
  File "D:\AI\Auto-GPT\scripts\main.py", line 286, in <module>
    memory = PineconeMemory()
  File "D:\AI\Auto-GPT\scripts\config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "D:\AI\Auto-GPT\scripts\memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 236, in GET
    return self.request("GET", url,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1259, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object
Press any key to continue . . .
```

**Comment by nekohacker591** [comment]
same

**Comment by contactatfp** [comment]
I switched my Pinecone APIs from environment variables to using the .env file directly and it worked.

**Comment by SecureScript** [comment]
Same thing happened to me.

**Comment by mrpez1** [comment]
On the 5th command, I get empty command arguments:
 NEXT ACTION:  COMMAND =  ARGUMENTS = {}

**Comment by arzhangv** [comment]
Same here

**Comment by ajwong** [comment]
Same

**Comment by rop2000** [comment]
Same

**Comment by 2b3pro** [comment]
Same

**Comment by hariitsolutions** [comment]
Pinecode api and search engine  important?

**Comment by dmwyatt** [comment]
Don't keep repeating, just thumbs up the original comment rather than saying "same" or whatever.

**Comment by 2b3pro** [comment]
I encountered this error on my Mac running Catalina. I discovered an anomaly. 

While I renamed my .env file in the Finder, the file itself was actually NOT renamed when I brought up the directory listing in Terminal. So to resolve it, I performed this command: `mv .env.template .env`

Then ran `scripts/main.py` again. It worked.

**Comment by ExoSilica** [comment]
I think I found the solution you guys, and it has been working for some time now.

Basically this is what I've done to achieve my solution:
1. Uninstall Python 3.10.6 Installed the latest Python 3.10.11
2. Git cloned a fresh Auto-GPT
3. Install the requirement in the Auto-GPT dir.
4. I think this is the most important part:
Previously prior to git pull Auto-GPT it was working properly but once I updated Auto-GPT it stopped working but the issues are:
- Because I did not have a Pinecone API I've left it blank
- I accidently didn't paste the correct OpenAI API key since I did not remove the your- part of "your-api-key"
Solution:
- I went to Pinecone website and made a free account, got the API key and the region key and entered both of that for the Pinecone request.
- I made a new Open AI API key and applied that to the OpenAI Key.
- I added my Elevenlab API even though I was out of reddit. But I don't think this is as important.

![image](https://user-images.githubusercontent.com/115336928/230512848-86301368-890a-401d-ac26-20bd55233164.png)

All in all. I think the most important part of all this is make sure all API entries and region are met, if you don't have the API key, sign up and get a free one from all 3 of these platforms. Double check to make sure the entries are correct, if not make a new key, applied and try again.

Thanks all for following me through this journey.

**Comment by hariitsolutions** [comment]
@![image](https://user-images.githubusercontent.com/129013706/230514043-22dae36e-fcf7-4539-831b-3bf3fba55593.jpeg)

I am getting API rate limit Reached after updating pinecone memory api

**Comment by ExoSilica** [comment]
> @![image](https://user-images.githubusercontent.com/129013706/230514043-22dae36e-fcf7-4539-831b-3bf3fba55593.jpeg)
> 
> I am getting API rate limit Reached after updating pinecone memory api

Look like you reach your API limit, try making a new API key or new account with the API key and try again?
