### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by NetRunnerBlackwall** [Torantulino/Auto-GPT#360]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. run scripts/main.py after following the installation instructions to the letter
2. Get an error 

### Current behavior 😯

The error I'm receiving comes after answering the prompts, or returning from a session to "Would you like me to return to being Machine Name?"

`Traceback (most recent call last):
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0fe2c1c130>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/netcrawler/Auto-GPT/scripts/main.py", line 286, in <module>
    memory = PineconeMemory()
  File "/home/netcrawler/Auto-GPT/scripts/config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "/home/netcrawler/Auto-GPT/scripts/memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "/home/netcrawler/.local/lib/python3.10/site-packages/pinecone/manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "/home/netcrawler/.local/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/netcrawler/.local/lib/python3.10/site-packages/pinecone/core/client/api/index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/home/netcrawler/.local/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/home/netcrawler/.local/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/home/netcrawler/.local/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/home/netcrawler/.local/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "/home/netcrawler/.local/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 236, in GET
    return self.request("GET", url,
  File "/home/netcrawler/.local/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/netcrawler/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='controller.your-pinecone-region.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0fe2c1c130>: Failed to establish a new connection: [Errno -2] Name or service not known'))
`

### Expected behavior 🤔

Well, I've installed all of the requirements, and the API key is in the appropriate file, so my expectation is that it would continue past this error and allow me to exchange with the LLM.

### Your prompt 📝

I didn't get to the prompt even.

**Comment by Jimgitsit** [comment]
Same here.

**Comment by lamjys** [comment]
Same here too.

**Comment by ryanstull** [comment]
Same

**Comment by avancebt** [comment]
+1
no idea what to try to fix

**Comment by AntouanK** [comment]
same for all of us I guess

**Comment by AntouanK** [comment]
edit : I added the pinecone key and region, and it works fine now.

**Comment by lamjys** [comment]
Good idea, it works for me.

**Comment by bonsaihorn** [comment]
Ah I thought it might have been because I set my api as an environment
variable
