### ISSUE TITLE
ModuleNotFoundError: No module named 'readability' (when run script first time)

### ISSUE THREAD

**Issue by xSNYPSx** [Torantulino/Auto-GPT#37]
Auto-GPT\scripts>python main.py continuous-mode
Traceback (most recent call last):
  File "C:\Users\ixliv\Auto-GPT\scripts\main.py", line 3, in <module>
    import commands as cmd
  File "C:\Users\ixliv\Auto-GPT\scripts\commands.py", line 1, in <module>
    import browse
  File "C:\Users\ixliv\Auto-GPT\scripts\browse.py", line 4, in <module>
    from readability import Document
ModuleNotFoundError: No module named 'readability'

**Comment by xSNYPSx** [comment]
oh sorry, just use pip install readability-lxml

**Comment by AndresCdo** [comment]
Is this package in the "requirements" file? 

> oh sorry, just use pip install readability-lxml
