### ISSUE TITLE
conn = connection.create_connection

### ISSUE THREAD

**Issue by mathewwalker** [Torantulino/Auto-GPT#380]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Python\Python311\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000016011AAEC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mathew\Documents\Stable Difusion\AutoChatGPT\Auto-GPT\scripts\main.py", line 286, in <module>
    memory = PineconeMemory()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\Documents\Stable Difusion\AutoChatGPT\Auto-GPT\scripts\config.py", line 17, in __call__
    cls._instances[cls] = super(
                          ^^^^^^
  File "C:\Users\Mathew\Documents\Stable Difusion\AutoChatGPT\Auto-GPT\scripts\memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 439, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py", line 236, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mathew\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='controller.your-pinecone-region.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016011AAEC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

C:\Users\Mathew\Documents\Stable Difusion\AutoChatGPT\Auto-GPT>

### Current behavior 😯

I get as far as goals and after adding 3 and entering blank it returns error message.

### Expected behavior 🤔

cmd run error after using 3.5gpt.

### Your prompt 📝

```yaml
ai_goals:
- Increase net worth
- Grow twitter
- Grow email subscriber list
ai_name: Alcoholfree-GPT
ai_role: An AI designed to autonomously develop and run an alcohol-free website to
  increase its net worth.```

**Comment by nithronium** [comment]
Setup pinecone API keys.

**Comment by nofreewill42** [comment]
Same error for me, even after setting up pinecone.

**Comment by ABOBALOYI** [comment]
did you all paste and save the pinecone region and API key on .env?

**Comment by nofreewill42** [comment]
My bad, I've opened .env.template, renamed it to .env and only after that I've added the API keys to it and saving it created the .env.template again, not saving to .env
Now it's working, thanks!

**Comment by mathewwalker** [comment]
check working fine now. thanks @nithronium
