### ISSUE TITLE
After prompt "Name or service not known"

### ISSUE THREAD

**Issue by lacer2k** [Torantulino/Auto-GPT#385]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

root@docker201021onubuntu2204-s-1vcpu-1gb-amd-fra1-01:~/Auto-GPT# python3 scripts/main.py --gpt3only
GPT3.5 Only Mode:  ENABLED
Welcome back!  Would you like me to return to being test?
Continue with the last settings? 
Name:  test
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth', 'Grow Twitter Account', 'Develop and manage multiple businesses autonomously']  
Continue (y/n): y

### Current behavior 😯

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc5d8b11f00>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Auto-GPT/scripts/main.py", line 286, in <module>
    memory = PineconeMemory()
  File "/root/Auto-GPT/scripts/config.py", line 17, in __call__
    cls._instances[cls] = super(
  File "/root/Auto-GPT/scripts/memory.py", line 30, in __init__
    if table_name not in pinecone.list_indexes():
  File "/usr/local/lib/python3.10/dist-packages/pinecone/manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api/index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/rest.py", line 236, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='controller.your-pinecone-region.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc5d8b11f00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
root@docker201021onubuntu2204-s-1vcpu-1gb-amd-fra1-01:~/Auto-GPT# 

### Expected behavior 🤔

it shoud run the program

### Your prompt 📝

```yaml
an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
```

**Comment by lacer2k** [comment]
fixed, just use pinecone ;)

**Comment by toamitshah** [comment]
HI Lacer,

I also getting same error ... can you please share some detailed solution for this. I am not getting how exactly you fixed it above. I am trying to run this on ubuntu system
