### ISSUE TITLE
Connection Traceback Error - not able to run Auto-GPT

### ISSUE THREAD

**Issue by DerLerner** [Torantulino/Auto-GPT#387]
This is my error, hope someone can help me out :

kev@Kevins-Air Auto-GPT % python scripts/main.py                      
Welcome back!  Would you like me to return to being Helper?
Continue with the last settings? 
Name:  Helper
Role:  Role***
Goals: 5 Goals ***
Continue (y/n): y
Traceback (most recent call last):
  File "/Users/kev/Documents/AutoGPT/Auto-GPT/scripts/main.py", line 287, in <module>
    memory.clear()
  File "/Users/kev/Documents/AutoGPT/Auto-GPT/scripts/memory.py", line 46, in clear
    self.index.delete(deleteAll=True)
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/utils/error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/index.py", line 329, in delete
    return self._vector_api.delete(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/client/api/vector_operations_api.py", line 117, in __delete
    return self.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 207, in __call_api
    raise e
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/client/api_client.py", line 459, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/client/rest.py", line 271, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kev/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pinecone/core/client/rest.py", line 222, in request
    raise ForbiddenException(http_resp=r)
pinecone.core.client.exceptions.ForbiddenException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '0', 'date': 'Fri, 07 Apr 2023 11:48:13 GMT', 'server': 'envoy'})

**Comment by anthony-holley** [comment]
How did you resolve this?

**Comment by ERANODE** [comment]
I managed to resolve the issue after making sure the Pinecone env, Pinecone api, OpenAI API, and Elevenlabs API were all properly listed in the .env. In the case where people don't have the --speak flag enabled, the Elevenlabs API probably isn't necessary.
