### ISSUE TITLE
Image generator error

### ISSUE THREAD

**Issue by rockierock** [Torantulino/Auto-GPT#518]
### Image GEN error

- [X] I have searched the existing issues

### Steps to reproduce 🕹

After installing the requirements.txt and modifying the .env file, I ran the main.py and faced this issue.

### Current behavior 😯

C:\Users\rockie\Downloads\Auto-GPT-master\Auto-GPT-master> python scripts/main.py
Traceback (most recent call last):
  File "C:\Users\rockie\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\main.py", line 3, in <module>
    import commands as cmd
  File "C:\Users\rockie\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\commands.py", line 12, in <module>
    from image_gen import generate_image
  File "C:\Users\rockie\Downloads\Auto-GPT-master\Auto-GPT-master\scripts\image_gen.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

### Expected behavior 🤔

Normal prompt Output

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Scn64** [comment]
You'll need to install pillow. Type "pip install Pillow" at the command prompt before starting AutoGPT.

**Comment by JeremyFabrikapp** [comment]
#482 fix this !

**Comment by Torantulino** [comment]
Fixed in #482
