### ISSUE TITLE
ModuleNotFoundError: No module named 'orjson' after pulling the latest version of the main branch

### ISSUE THREAD

**Issue by MchLrnX** [Torantulino/Auto-GPT#617]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

git pull in the most recent main
run main.py from the script's folder.

### Current behavior 😯

Traceback (most recent call last):
  File "/home/parallels/Auto-GPT/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "/home/parallels/Auto-GPT/scripts/commands.py", line 3, in <module>
    from memory import get_memory
  File "/home/parallels/Auto-GPT/scripts/memory/__init__.py", line 1, in <module>
    from memory.local import LocalCache
  File "/home/parallels/Auto-GPT/scripts/memory/local.py", line 2, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

### Expected behavior 🤔

I expected the file to launch

### Your prompt 📝

```yaml
# Paste your prompt here
```

NA

**Comment by richbeales** [comment]
`pip install -r requirements.txt`

**Comment by MchLrnX** [comment]
Ah you rock, that was exactly it. Thank you!
