### ISSUE TITLE
ModuleNotFoundError: No module named 'UserDict' - MacOS Ventura

### ISSUE THREAD

**Issue by techsteramman** [Torantulino/Auto-GPT#65]
from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'

**Comment by nathanlannan** [comment]
Seconded on Windows:
from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'

**Comment by theref** [comment]
+1

**Comment by PhilipAD** [comment]
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/path/to/main.py", line 3, in <module>
import commands as cmd
File "/path/to/commands.py", line 8, in <module>
import ai_functions as ai
File "/path/to/ai_functions.py", line 5, in <module>
from json_parser import fix_and_parse_json
File "/path/to/json_parser.py", line 1, in <module>
import dirtyjson
File "/path/to/anaconda3/envs/auto-gpt/lib/python3.11/site-packages/dirtyjson/init.py", line 33, in <module>
from .loader import DirtyJSONLoader
File "/path/to/anaconda3/envs/auto-gpt/lib/python3.11/site-packages/dirtyjson/loader.py", line 8, in <module>
from dirtyjson.attributed_containers import AttributedDict, AttributedList
File "/path/to/anaconda3/envs/auto-gpt/lib/python3.11/site-packages/dirtyjson/attributed_containers.py", line 11, in <module>
from UserDict import DictMixin
ModuleNotFoundError: No module named ‘UserDict'
```

**Comment by OneRain233** [comment]
+1

**Comment by szerlok** [comment]
+1

**Comment by theopencity** [comment]
Got similar error. Someone help

**Comment by Cosmingld** [comment]
Run the error on chatgpt-4 itll give u answers to fix

**Comment by PhilipAD** [comment]
https://github.com/Torantulino/Auto-GPT/pull/67

**Comment by chrgeor** [comment]
I have the same issue in windows with venv python 3.10.9

**Comment by PhilipAD** [comment]
> Is there a simpler fix than that? Anyone got this working, I'm not able to reproduce...

I tried monkey patching but it doesn't seem to import correctly

**Comment by theopencity** [comment]
Thanks  @sparkcomputers this fixed it for me.

> I fixed this error by find and replacing
> 
> `from collections import MutableMapping` to `from collections.abc import MutableMapping`

**Comment by Torantulino** [comment]
@theopencity Where are you finding that import?

**Comment by PhilipAD** [comment]
> @theopencity Where are you finding that import?

I think they are referring to changing their locally stored package site-packages/dirtyjson driecrtly.

**Comment by chrgeor** [comment]
that's right, it is in my venv `...\Auto-GPT\venv\lib\python3.8\site-packages\dirtyjson\attributed_containers.py`

```python
    from collections import MutableMapping as DictMixin
```

**Comment by Torantulino** [comment]
Fixed in #68
