### ISSUE TITLE
module 'tiktoken' has no attribute 'encoding_for_model'

### ISSUE THREAD

**Issue by 0xech0** [Torantulino/Auto-GPT#76]
Getting this error on OS X, even tho it seems like tiktoken is installed correctly

Traceback (most recent call last):
  File "/Users/echo/Auto-GPT/scripts/main.py", line 286, in <module>
    assistant_reply = chat.chat_with_ai(
  File "/Users/echo/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "/Users/echo/Auto-GPT/scripts/token_counter.py", line 16, in count_message_tokens
    encoding = tiktoken.encoding_for_model(gpt-4)
AttributeError: module 'tiktoken' has no attribute 'encoding_for_model'

**Comment by Torantulino** [comment]
This means you have the wrong version of tiktoken installed.

Try updating it to 0.3.3.

**Comment by 0xech0** [comment]
ah ty, got messed up when changing requirements to run on m1 mac. works now!
