### ISSUE TITLE
cfg.debug not init

### ISSUE THREAD

**Issue by SuperJT** [Torantulino/Auto-GPT#841]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I have been attempting to run through the initial install with auto-gpt.  upon submitting goals i get 
1) jtownsen@jtownsen-mac-1 auto-gpt % pip install -r requirements.txt
2) configure .env (mv .env.template .env)

At this point I ran main.py and got to the point of goals being configured then i get this error:
jtownsen@jtownsen-mac-1 auto-gpt % python3 scripts/main.py
Welcome back!  Would you like me to return to being storage-gpt?
Continue with the last settings?
Name:  storage-gpt
Role:  an AI designed to understand the complexity of technical support issues and the protocols associated with storage access.  Using this understanding to build tools to automate understanding the customers context and associating problmes to this context.
Goals: ['learn how to troubleshoot storage related issues via netapp logs', 'learn how to understand issues related to nas protocols from pcap analysis', 'build knowledge to share this understanding to multiple users', 'follow KCSv6 principals']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/Users/jtownsen/bin/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/jtownsen/bin/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
       ^^^^^^^^^
AttributeError: 'Config' object has no attribute 'debug'

### Current behavior 😯

Welcome back!  Would you like me to return to being storage-gpt?
Continue with the last settings?
Name:  storage-gpt
Role:  an AI designed to understand the complexity of technical support issues and the protocols associated with storage access.  Using this understanding to build tools to automate understanding the customers context and associating problmes to this context.
Goals: ['learn how to troubleshoot storage related issues via logs', 'learn how to understand issues related to nas protocols from pcap analysis', 'build knowledge to share this understanding to multiple users', 'follow KCSv6 principals']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/Users/jtownsen/bin/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/jtownsen/bin/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
       ^^^^^^^^^
AttributeError: 'Config' object has no attribute 'debug'

### Expected behavior 🤔

Doesnt seem to be a way to init this debug variable manually. 
Looking at the config.py file it looks like it should be init already.

class Config(metaclass=Singleton):
    """
    Configuration class to store the state of bools for different scripts access.
    """

    def __init__(self):
        """Initialize the Config class"""
        self.debug_mode = False
        self.continuous_mode = False
        self.speak_mode = False

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by SuperJT** [comment]
I found this after i posted.

https://github.com/Torantulino/Auto-GPT/issues/803
