### ISSUE TITLE
Human Feedback Error "substring not found"

### ISSUE THREAD

**Issue by Chase0x** [Torantulino/Auto-GPT#906]
```
TWITTER ACCOUNT MANAGEMENT-GPT THOUGHTS: Before creating Twitter accounts for each niche, I should do a little more research on each niche to identify account details, including the best language to use, tone of voice to adopt, content type
 to focus on, and the right Twitter handles and hashtags. This will help me establish the presence of each twitter account as unique and more easy to recognize, which will work towards greater engagement and growth on each account.
REASONING: I believe further research on our niches and keywords is vital for developing effective content strategies and creation of compelling Twitter handles, which increases recognition and reach. Research will help us to develop more targeted content and personalized strategies suited to our audience. Consideration to Twitter handles and hashtags is vital in delivering a unique identity to each account that can quickly separate followers across different accounts.
PLAN:
-  Conduct some more research on each niche to identify new account details.
-  Create personalized strategies for each Twitter handle.
-  Ensure each account detail is customizable to resonate with our audience.
CRITICISM: Though research is essential, to avoid analysis paralysis, we need to make sure not to overdo it. As we execute our plan, we should keep in mind that continuous improvement is possible only by actively engaging with our audience and consistently providing value to our niche topics.
NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for Twitter Account Management-GPT...
Input:Are you ready to create the twitter accounts and export the information so that i can formally create them?
SYSTEM:  Human feedback: Are you ready to create the twitter accounts and export the information so that i can formally create them?
Error:
 Traceback (most recent call last): File "C:\Users\chase\Desktop\AI\Auto-GPT\scripts\main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "C:\Users\chase\Desktop\AI\Auto-GPT\scripts\json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found
NEXT ACTION:  COMMAND = Error: ARGUMENTS = substring not found
```

**Comment by Chase0x** [comment]
> have you managed to find fix for this?

Not yet, unfortunately

**Comment by jaredhilton** [comment]
Take a look at the changes made in this PR and make the same changes: https://github.com/Torantulino/Auto-GPT/pull/895.

**Comment by Chase0x** [comment]
> Take a look at the changes made in this PR and make the same changes: #895.

Great, thank you, missed the changes to json_parser.py
