### ISSUE TITLE
Installation issue with 'googlesearch-python'

### ISSUE THREAD

**Issue by ezzcodeezzlife** [Torantulino/Auto-GPT#95]
```
git clone https://github.com/Torantulino/Auto-GPT.git
cd 'Auto-GPT'
```
now when running:
```
pip install -r requirements.txt
```

i get this error:
```
...
Collecting docker
  Using cached docker-6.0.1-py3-none-any.whl (147 kB)
Collecting googlesearch-python
  Using cached googlesearch-python-1.2.0.tar.gz (7.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-b0kbesj5/googlesearch-python_0639a0155ff34a7eab229bcab3849788/setup.py", line 6, in <module>
          with open("requirements.txt") as fh:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

```
ls
```
```
Dockerfile  LICENSE  README.md  outputs  requirements-alternative.txt  requirements.txt  scripts  tests
```

**Comment by DamascusGit** [comment]
> In a new directory, clone the package: `https://github.com/Nv7-GitHub/googlesearch.git`
> 
> then: `cd googlesearch` `echo "beautifulsoup4==4.9.3" > requirements.txt` `pip install .`
> 
> Now go back to Auto-GPT directory and run `pip install -r requirements.txt`
> 
> should work now

this is the fix. thanks.

**Comment by stri8ed** [comment]
> new release issues 1 hour ago is not working, downgrade
> 
> pip install googlesearch-python==1.1.0

This causes another problem:

`ERROR: Cannot install -r requirements.txt (line 3), -r requirements.txt (line 9), googlesearch-python==1.1.0 and requests because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests
    openai 0.27.2 depends on requests>=2.20
    tiktoken 0.3.3 depends on requests>=2.26.0
    googlesearch-python 1.1.0 depends on requests==2.25.1
`

**Comment by n2nco** [comment]
on mac used:

```
pip install git+https://github.com/Nv7-GitHub/googlesearch.git
```

and it's working

**Comment by p-marb** [comment]
> In a new directory, clone the package: `https://github.com/Nv7-GitHub/googlesearch.git`
> 
> then: `cd googlesearch` `echo "beautifulsoup4==4.9.3" > requirements.txt` `pip install .`
> 
> Now go back to Auto-GPT directory and run `pip install -r requirements.txt`
> 
> should work now

this worked for me too, just make sure that requirements.txt is saved as UTF-8!! thanks

**Comment by mbledkowski** [comment]
Same issue on Arch Linux distrobox running over NixOS
```console
$ sudo pip install -r ./requirements-alternative.txt                                                                                                                                                                                                ~/.b/Auto-GPT ✘ 1 master ✖
Collecting docker==5.0.3
  Using cached docker-5.0.3-py2.py3-none-any.whl (146 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.12.0-py3-none-any.whl (132 kB)
Collecting colorama==0.4.6
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting openai==0.27.2
  Using cached openai-0.27.2-py3-none-any.whl (70 kB)
Collecting playsound==1.3.0
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Preparing metadata (setup.py) ... done
Collecting python-dotenv==1.0.0
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting pyyaml==6.0
  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
Collecting readability-lxml==0.8.1
  Using cached readability_lxml-0.8.1-py3-none-any.whl (20 kB)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting tiktoken==0.3.3
  Using cached tiktoken-0.3.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
Collecting googlesearch-python
  Using cached googlesearch-python-1.2.0.tar.gz (7.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9e_4webh/googlesearch-python_4f7ba4927a874a57a14e0ffb0dc49db0/setup.py", line 6, in <module>
          with open("requirements.txt") as fh:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mbledkowski** [comment]
> on mac used:
> 
> ```
> pip install git+https://github.com/Nv7-GitHub/googlesearch.git
> ```
> 
> and it's working

Replacing googlesearch-python in requirements.txt, with git+https://github.com/Nv7-GitHub/googlesearch.git helped in my case
