### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by DamascusGit** [Torantulino/Auto-GPT#99]
Getting this error after running the main.py file.

```
Traceback (most recent call last):
  File "/autogpt/Auto-GPT/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "/autogpt/Auto-GPT/scripts/commands.py", line 1, in <module>
    import browse
  File "/autogpt/Auto-GPT/scripts/browse.py", line 2, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

**Comment by xpghard** [comment]
@DamascusGit 
You don't have module BeautifulSoup4
run in cmd ```
pip install beautifulsoup4
```

**Comment by DamascusGit** [comment]
yes i do

**Comment by CannibalKush** [comment]
If you're getting this, ensure `pip install -r requirements.txt` ran correctly, for me the issue was simply that i had to run cmd as administrator

**Comment by decherneyge** [comment]
can confirm still getting this error on windows and installing as admin . Its probably something obvious to a regular user of python but as I am not I am stumped. 
![image](https://user-images.githubusercontent.com/654448/231607584-e08a9fb6-a925-4996-aae8-96b7fecd1f78.png)

**Comment by evertjwa** [comment]
Your'e not the only one, I'm struggling already for the third day with exactly the same problem. I use python 3.9 on my Macbook air m2. I have used bs4 and beautifulsoup before without any problems. It seems to me that the product AUTO-GPT is not stable enough for use yet.

**Comment by malekhijazi** [comment]
I have an M1 Pro Macbook, and I'm facing the same issue. 

For some reason running `pip install -r requirements.txt` doesn't install all dependencies.

But using the below seems to work. 

```
python -m pip install -r requirements.txt
```

After that, run the `main.py` script, and it should work

**Comment by rishabhv333** [comment]
> I have an M1 Pro Macbook, and I'm facing the same issue.
> 
> For some reason running `pip install -r requirements.txt` doesn't install all dependencies.
> 
> But using the below seems to work.
> 
> ```
> python -m pip install -r requirements.txt
> ```
> 
> After that, run the `main.py` script, and it should work

It worked for me thanks!

**Comment by Arpiet21** [comment]
PS D:\Download\Auto-GPT-master> python3 d:\Download\Auto-GPT-master\scripts\main.py     
Traceback (most recent call last):
  File "d:\Download\Auto-GPT-master\scripts\main.py", line 3, in <module>
    import commands as cmd
  File "d:\Download\Auto-GPT-master\scripts\commands.py", line 1, in <module>
    import browse
  File "d:\Download\Auto-GPT-master\scripts\browse.py", line 3, in <module>
    from config import Config
  File "d:\Download\Auto-GPT-master\scripts\config.py", line 3, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
PS D:\Download\Auto-GPT-master> 

Getting this error again again

**Comment by astrodooog** [comment]
> pip install -r requirements.txt

thank you very much!! it is helpful!
